ATTR keyword media-supported om_tape-auto_300x36mm
ATTR keyword media-ready om_tape-auto_300x36mm
ATTR keyword media-default om_tape-auto_300x36mm
ATTR keyword urf-supported V1.4,CP1,RS360,W8,DM1
ATTR resolution printer-resolution-supported 360dpi
ATTR resolution printer-resolution-default 360dpi
ATTR resolution pwg-raster-document-resolution-supported 360dpi
ATTR keyword pwg-raster-document-type-supported black_1,sgray_8
ATTR keyword pwg-raster-document-sheet-back normal
ATTR keyword sides-supported one-sided
ATTR keyword sides-default one-sided
ATTR integer media-top-margin-supported 0
ATTR integer media-bottom-margin-supported 0
ATTR integer media-left-margin-supported 0
ATTR integer media-right-margin-supported 0
ATTR mimeMediaType document-format-supported application/pdf
ATTR collection media-col-database {
  MEMBER collection media-size {
    MEMBER integer x-dimension 30000
    MEMBER integer y-dimension 3600
  }
  MEMBER integer media-top-margin 0
  MEMBER integer media-bottom-margin 0
  MEMBER integer media-left-margin 0
  MEMBER integer media-right-margin 0
}
ATTR collection media-size-supported {
  MEMBER collection media-size {
    MEMBER integer x-dimension 30000
    MEMBER integer y-dimension 3600
  }
  MEMBER integer media-top-margin 0
  MEMBER integer media-bottom-margin 0
  MEMBER integer media-left-margin 0
  MEMBER integer media-right-margin 0
},{
  MEMBER rangeOfInteger x-dimension 500-100000
  MEMBER rangeOfInteger y-dimension 3500-3700
}
